//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExample.DB
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using Microsoft.EntityFrameworkCore.SqlServer;
    using NetTopologySuite.Geometries;
    using System.ComponentModel.DataAnnotations.Schema;

    public partial class Orders
    {
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long id { get; set; }
        public string id_client { get; set; }
        public Nullable<long> id_turns { get; set; }
        public System.DateTime date_start_order { get; set; }
        public Nullable<System.DateTime> date_start_trip { get; set; }
        public Nullable<System.DateTime> date_end_trip { get; set; }
        public int id_order_type { get; set; }
        public double start_point_lat { get; set; }
        public double start_point_long { get; set; }
        public double end_point_lat { get; set; }
        public double end_point_long { get; set; }
        public int security_code { get; set; }
        public bool confirmed { get; set; }
        public bool pets { get; set; }
        public bool child { get; set; }
        public bool driver_confirm_end { get; set; }
        public bool client_confirm_end { get; set; }

        [ForeignKey("id_client")]
        public virtual Clients Clients { get; set; }
        [ForeignKey("id_order_type")]
        public virtual Order_types Order_types { get; set; }
        [ForeignKey("id_turns")]
        public virtual Turns Turns { get; set; }
    }
}
