//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestExample.DB
{
    using Microsoft.EntityFrameworkCore;
    using System;
    
    public partial class TaxiStationContext : DbContext
    {
        public TaxiStationContext(DbContextOptions<TaxiStationContext> options)
            : base(options)
        {
        }
    
        public virtual DbSet<Body_types> Body_types { get; set; }
        public virtual DbSet<Clients> Clients { get; set; }
        public virtual DbSet<Drivers> Drivers { get; set; }
        public virtual DbSet<Order_types> Order_types { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Turns> Turns { get; set; }
        public virtual DbSet<Venichles> Venichles { get; set; }
    }
}
